# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run YARA-Forge

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install CMake and Ninja
      run: sudo apt-get install -y cmake ninja-build

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install RE2
      run: sudo apt-get install -y libre2-dev

    - name: Install dependencies for yaraQA
      run: |
        python -m pip install --upgrade pip
        if [ -f qa/yaraQA/requirements.txt ]; then pip install -r qa/yaraQA/requirements.txt; fi

    - name: Run YARA-Forge
      run: |
        python yara-forge.py
